# Generated by Django 5.1.7 on 2025-04-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_auto_20250413_1008'),
    ]

    operations = [
    ]
