# Generated by Django 5.1.7 on 2025-04-13 10:13

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_auto_20250413_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkuser',
            name='clerk_user_id',
            field=models.CharField(max_length=255, unique=True, null=True, blank=True),
        ),
    ]