# Generated by Django 5.1.7 on 2025-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0008_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='description',
            new_name='image_full_url',
        ),
        migrations.AddField(
            model_name='board',
            name='image_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='board',
            name='image_link_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='board',
            name='image_thumb_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='board',
            name='image_username',
            field=models.TextField(blank=True),
        ),
    ]
