# Generated by Django 5.1.7 on 2025-04-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0010_list_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='listId',
        ),
        migrations.RemoveField(
            model_name='list',
            name='boardId',
        ),
    ]
