# Generated by Django 5.1.7 on 2025-04-29 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0011_remove_card_listid_remove_list_boardid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('entityId', models.CharField(max_length=255)),
                ('entityType', models.CharField(choices=[('BOARD', 'Board'), ('LIST', 'List'), ('CARD', 'Card')], max_length=10)),
                ('entityTitle', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=255, null=True)),
                ('userImage', models.TextField()),
                ('userName', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.organization')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
