# Generated by Django 5.1.7 on 2025-04-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0012_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('COPY', 'Copy')], max_length=10),
        ),
    ]
