# Generated by Django 5.1.7 on 2025-05-05 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0015_orgsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('colr', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.organization')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='cards', to='my_auth.color'),
        ),
    ]
