# Generated by Django 5.1.7 on 2025-05-05 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0016_color_card_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='Board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_auth.board'),
            preserve_default=False,
        ),
    ]
