# Generated by Django 5.1.7 on 2025-05-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0017_color_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='colr',
            new_name='color',
        ),
    ]
