# Generated by Django 5.1.7 on 2025-05-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0018_rename_colr_color_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='Board',
            new_name='board',
        ),
    ]
