# Generated by Django 5.1.7 on 2025-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0019_rename_board_color_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=255),
        ),
    ]
