# Generated by Django 5.1.7 on 2025-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0020_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entityType',
            field=models.CharField(choices=[('BOARD', 'Board'), ('LIST', 'List'), ('CARD', 'Card'), ('COLOR', 'Color'), ('DESCRIPTION', 'Description')], max_length=14),
        ),
    ]
