# Generated by Django 5.1.7 on 2025-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0021_alter_auditlog_entitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(blank=True, to='my_auth.color'),
        ),
    ]
