# Generated by Django 5.1.7 on 2025-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0022_alter_card_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='reminder_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
