# Generated by Django 5.1.7 on 2025-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0023_card_due_date_card_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='time_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
