# Generated by Django 5.1.7 on 2025-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0024_card_start_date_card_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='time_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
