# Generated by Django 5.1.7 on 2025-05-08 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0025_alter_card_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='assigned_cards', to='my_auth.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
