# Generated by Django 5.1.7 on 2025-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0027_alter_card_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkuser',
            name='userImage',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
