# Generated by Django 5.1.7 on 2025-05-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0028_clerkuser_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkuser',
            name='userImage',
            field=models.TextField(blank=True),
        ),
    ]
