# Generated by Django 5.1.7 on 2025-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0030_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entityType',
            field=models.CharField(choices=[('BOARD', 'Board'), ('LIST', 'List'), ('CARD', 'Card'), ('COLOR', 'Color'), ('DESCRIPTION', 'Description'), ('ATTACHEMENT', 'Attachement')], max_length=14),
        ),
    ]
