# Generated by Django 5.1.7 on 2025-05-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0031_alter_auditlog_entitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entityType',
            field=models.CharField(choices=[('BOARD', 'Board'), ('LIST', 'List'), ('CARD', 'Card'), ('COLOR', 'Color'), ('DESCRIPTION', 'Description'), ('ATTACHMENT', 'ATTACHMENT')], max_length=14),
        ),
    ]
