# Generated by Django 5.1.7 on 2025-05-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0033_alter_attachment_file_alter_auditlog_entitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
