# Generated by Django 5.1.7 on 2025-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0034_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entityType',
            field=models.CharField(choices=[('BOARD', 'Board'), ('LIST', 'List'), ('CARD', 'Card'), ('COLOR', 'Color'), ('DESCRIPTION', 'Description'), ('ATTACHMENT', 'Attachment'), ('COMMENT', 'Comment')], max_length=14),
        ),
    ]
