# Generated by Django 5.1.7 on 2025-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0035_alter_auditlog_entitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_description',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
