# Generated by Django 5.1.7 on 2025-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0036_auditlog_action_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entityBoard',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
