# Generated by Django 5.1.7 on 2025-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0037_auditlog_entityboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
